### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by jonathan-bird** [czim/laravel-cms-core#1]
This CMS looks perfect for what I'm looking to do - there's basically no drop-in CMS solutions for Laravel surprisingly.

When are you looking to add Laravel 5.4 support? Would be great to have soon!

**Comment by czim** [comment]
Yeah, I was pretty suprised myself that there were no free solutions for a custom drop in CMS. Everything seems to want to turn Laravel into Wordpress, or is too restrictive in one way or another.

Support for 5.4 definitely on the short-term list. I'm currently completing tests for 5.3 for the core, then I can handle Laravel 5.4. 

The only thing that will delay this quite a bit, is [this 5.4 issue](https://github.com/laravel/internals/issues/391), especially for the Models Module.

Update:
There are also problems with the API, since the discontinued OAuth dependency does not work with Laravel 5.4. I cannot switch to Passport, since it is not suited for running parallel, independent API's, so another solution must be found for the CMS API to be usable in 5.4.

**Comment by czim** [comment]
A small update on my progress so far: I've got the web basics for the core and [authentication](https://github.com/czim/laravel-cms-auth) component working in Laravel 5.4. 

I don't have enough test coverage to know whether the [models module](https://github.com/czim/laravel-cms-models) works well enough, but it performs okay in manual tests.

If anyone wants to play around with this, just `dev-laravel-5.4` for the version in composer:

```
"require": {
    "czim/laravel-cms-core": "dev-laravel-5.4",
    "czim/laravel-cms-auth": "dev-laravel-5.4",
    "czim/laravel-cms-models": "dev-laravel-5.4",
}
```

The master versions for theme and ACL should work in 5.4 without problems.

**Comment by czim** [comment]
Another update: the core and auth component now have a `~1.4` version that is fully tested with Laravel 5.4. The API is also (as) functional (as in 5.3).

There are still issues with the models module.

**Comment by czim** [comment]
I'm happy to say the `~1.4` version for the models package is now getting pretty stable; With 86% test coverage it's nowhere near perfect yet, but it can definitely be used in Laravel 5.4.

Any feedback on this is very welcome. If anything does crop up, I intend to fix it ASAP.

**Comment by daniel-de-wit** [comment]
Trying to update my project to Laravel 5.4.* gives me the following error message when running composer update:

Problem 1
    - czim/laravel-cms-core dev-master requires laravel/framework 5.3.*

**Comment by czim** [comment]
`dev-master` is For Laravel 5.3. For 5.4, use version `~1.4.0`.
